// src/constants/applicationStatus.js

const APPLICATION_STATUS = Object.freeze({
  DRAFT: "DRAFT",

  DOCUMENT_PENDING: "DOCUMENT_PENDING",

  DOCUMENT_SUBMITTED: "DOCUMENT_SUBMITTED",

  UNDER_REVIEW: "UNDER_REVIEW",

  CORRECTION_REQUIRED: "CORRECTION_REQUIRED",

  DOCUMENT_RESUBMITTED: "DOCUMENT_RESUBMITTED",

  DOCUMENT_VERIFIED: "DOCUMENT_VERIFIED",

  DEPARTMENT_APPROVED: "DEPARTMENT_APPROVED",

  DEPARTMENT_REJECTED: "DEPARTMENT_REJECTED",

  PAYMENT_PENDING: "PAYMENT_PENDING",

  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",

  PAYMENT_VERIFICATION_PENDING: "PAYMENT_VERIFICATION_PENDING",

  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",

  PAYMENT_REJECTED: "PAYMENT_REJECTED",

  DEAN_APPROVED: "DEAN_APPROVED",

  DEAN_REJECTED: "DEAN_REJECTED",

  REGISTERED: "REGISTERED",
});

module.exports = APPLICATION_STATUS;