const DOCUMENT_TYPES = Object.freeze({
  SSC_MARKSHEET: "SSC_MARKSHEET",
  SSC_CERTIFICATE: "SSC_CERTIFICATE",
  HSC_MARKSHEET: "HSC_MARKSHEET",
  HSC_CERTIFICATE: "HSC_CERTIFICATE",
  STUDENT_PHOTO: "STUDENT_PHOTO",
  BIRTH_CERTIFICATE: "BIRTH_CERTIFICATE",
});

module.exports = DOCUMENT_TYPES;